#!/bin/sh

##############################################################
# https://ffmpeg.org/trac/ffmpeg/wiki/UbuntuCompilationGuide #
##############################################################

# cd ~/ffmpeg_sources
# git clone --depth 1 git://source.ffmpeg.org/ffmpeg
# cd ffmpeg
# PKG_CONFIG_PATH="$HOME/ffmpeg_build/lib/pkgconfig"
# export PKG_CONFIG_PATH
# ./configure --prefix="$HOME/ffmpeg_build" \
#   --extra-cflags="-I$HOME/ffmpeg_build/include" --extra-ldflags="-L$HOME/ffmpeg_build/lib" \
#   --bindir="$HOME/bin" --extra-libs="-ldl" --enable-gpl --enable-libx264 --enable-nonfree
# make
# make install
# make distclean
# hash -r
