#!/bin/sh

# cd ~/ffmpeg_sources
# git clone --depth 1 git://git.videolan.org/x264.git
# cd x264
# ./configure --prefix="$HOME/ffmpeg_build" --bindir="$HOME/bin" --enable-static
# make
# make install
# make distclean

vulcan build -s ~/src/x264 -p /tmp/x264 -c "./autogen.sh && ./configure --prefix=/tmp/memcached && make install"
